apiVersion: apps/v1
kind: Deployment 
metadata:
  name: demo-docker
spec:
  selector:
    matchLabels:
      app: demo-docker
  replicas: 2 
  template:
    metadata:
      labels:
        app: demo-docker
    spec:
      containers:
        - name: demo-docker
          image: tithidebnath/demo_docker:latest
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 8080
            
            